---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  labels:
    name: app-ingress
spec:
  ingressClassName: traefik
  rules:
    - host: api.ayane0857.net
      http:
        paths:
          - pathType: Prefix
            path: /payment
            backend:
              service:
                name: ayane-payment-api
                port:
                  number: 80
