---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: payment-api-db
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /nfs/users/ayane/payment-api
    server: nfs.unipro.infra
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
  name: db
  labels:
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db
  labels:
    app: payment-api
spec:
  resources:
    requests:
      storage: 3Gi
  accessModes:
    - ReadWriteMany
  volumeName: payment-api-db
