apiVersion: v1
kind: PersistentVolume
metadata:
  name: paymentAPI-db
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /nfs/users/ayane/paymentAPI
    server: nfs.unipro.infra
  claimRef:
    namespace: paymentAPI
    name: db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db
  labels:
    app: paymentAPI
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteMany
  volumeName: paymentAPI-db
