apiVersion: v1
kind: PersistentVolume
metadata:
  name: paymentAPI-db
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /nfs/users/ayane/paymentAPI
    server: nfs.unipro.infra
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
  name: db
  labels:
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db
  labels:
    app: paymentAPI
spec:
  resources:
    requests:
      storage: 3Gi
  accessModes:
    - ReadWriteMany
  volumeName: paymentAPI-db
