name: Docker Build and Push
on:
  push:
    tags:
      - "v*"

jobs:
  BuildAndPush:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract tag name
        run: |
          tagname=${GITHUB_REF#refs/*/} && echo "TAG_NAME=${tagname#v}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: registry.uniproject.jp
          username: ayane
          password: ${{ secrets.HARBOR_TOKEN }}

      - name: Build Docker image
        run: docker build -t registry.uniproject.jp/ayane/payment-api:${{ env.TAG_NAME }} .

      - name: Push Docker image
        run: docker push registry.uniproject.jp/ayane/payment-api:${{ env.TAG_NAME }}
